openapi: 3.0.0
info:
  title: IP Block
  version: 1.0.0
paths:
  /health:
    get:
      responses:
        '200':
          description: teste
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK